spring.application.name=DealHunt

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/dealhunt?useSSL=false&serverTimezone=Asia/Kolkata&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

logging.level.com.dealhunt=INFO

dealhunt.ai.enabled=false
dealhunt.ai.api-key=
dealhunt.ai.model=

dealhunt.marketplaces.amazon.enabled=true
dealhunt.marketplaces.flipkart.enabled=true
dealhunt.marketplaces.myntra.enabled=true
dealhunt.marketplaces.meesho.enabled=true

dealhunt.marketplace.search-api-url=https://serpapi.com/search
dealhunt.marketplace.search-api-key=5166acdbad749ad960aaca570efcac1784c853af0c94da9c2c85219a3875da15